name: build

on:
  push:
    branches:
    - master
    - feat-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Build
      run: |
        npm run build
        rm -f $GITHUB_WORKSPACE/dist/*.json
    - name: Deploy to EO Pages
      env:
        EO_PAGE_NAME: ${{ secrets.EO_PAGE_NAME }}
        EO_PAGE_TOKEN: ${{ secrets.EO_PAGE_TOKEN }}
      run: npx edgeone pages deploy $GITHUB_WORKSPACE/dist -n $EO_PAGE_NAME -t $EO_PAGE_TOKEN
